# Generated by Django 5.1.4 on 2026-05-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="update_time",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="逻辑删除"),
        ),
    ]
