# Generated by Django 6.0.4 on 2026-07-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedWordDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="项目名称"
                    ),
                ),
                (
                    "report_no",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="报告编号"
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="原始文件名",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="保存文件名"),
                ),
                (
                    "relative_path",
                    models.CharField(max_length=500, verbose_name="相对文件路径"),
                ),
                (
                    "file_url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1000,
                        verbose_name="文件访问地址",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="文件大小"),
                ),
                (
                    "source_json",
                    models.JSONField(
                        blank=True, null=True, verbose_name="源 JSON 数据"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "成功"), ("failed", "失败")],
                        default="success",
                        max_length=20,
                        verbose_name="生成状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
            ],
            options={
                "verbose_name": "生成的 Word 文档",
                "verbose_name_plural": "生成的 Word 文档",
                "db_table": "tb_generated_word_document",
                "ordering": ("-create_time",),
            },
        ),
        migrations.CreateModel(
            name="ParsedReportJsonFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="项目名称"
                    ),
                ),
                (
                    "report_no",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="报告编号"
                    ),
                ),
                (
                    "source_docx_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="来源 Word 文件名",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="保存文件名"),
                ),
                (
                    "relative_path",
                    models.CharField(max_length=500, verbose_name="相对文件路径"),
                ),
                (
                    "file_url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1000,
                        verbose_name="文件访问地址",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="文件大小"),
                ),
                (
                    "parsed_json",
                    models.JSONField(
                        blank=True, null=True, verbose_name="解析后的 JSON 数据"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "成功"), ("failed", "失败")],
                        default="success",
                        max_length=20,
                        verbose_name="解析状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
            ],
            options={
                "verbose_name": "解析出的 JSON 文件",
                "verbose_name_plural": "解析出的 JSON 文件",
                "db_table": "tb_parsed_report_json_file",
                "ordering": ("-create_time",),
            },
        ),
    ]
